name: task_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  rxdart: ^0.25.0
  http: ^0.12.0+4
  animate_do: ^1.7.5
  socket_io_client: ^0.9.12
  socket_io_common_client: ^0.10.0
  web_socket_channel: ^1.2.0
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Nexa
      fonts:
        - asset: fonts/NexaXBold.otf
          weight: 900
        - asset: fonts/NexaBold.otf
          weight: 700
        - asset: fonts/NexaRegular.otf
          weight: 400
        - asset: fonts/NexaLight.otf
          weight: 100
